[package]
name = "openward-server"
description = "HTTP API server and frontend host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
openward-core.workspace = true
openward-facility.workspace = true
openward-registry.workspace = true
axum.workspace = true
tower-http.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
askama.workspace = true
askama_web.workspace = true
fluent-templates.workspace = true
unic-langid.workspace = true
toml.workspace = true
argon2.workspace = true
sqlx.workspace = true
openward-db.workspace = true
csv.workspace = true

[dev-dependencies]
regex.workspace = true
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
